### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by logicalelegance** [jnewc/SwiftUI-Validation#1]
Hi, I'd like to adapt this for a project I'm working on, but there's no license and I don't want to violate your copyright. Could you include a license in this repo or specify that you don't want this reused?

**Comment by jnewc** [comment]
@logicalelegance sorry for the long delay, this code was intended to be entirely open source / free to use. I'll add a license now 👍

**Comment by jnewc** [comment]
Added Apache 2.0 license.
